controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

product_details:
  path: /product/{id}
  controller: App\Controller\ProductController::showProdDetails

